# Generated by Django 5.2.7 on 2025-11-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="景点名称")),
                ("description", models.TextField(blank=True, verbose_name="景点描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "景点",
                "verbose_name_plural": "景点",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="uploads/", verbose_name="上传文件"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_type", models.CharField(max_length=50, verbose_name="文件类型")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        default="pending", max_length=100, verbose_name="处理状态"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
            ],
            options={
                "verbose_name": "上传文件",
                "verbose_name_plural": "上传文件",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="设备名称")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="位置/编号"),
                ),
                (
                    "equipment_type",
                    models.CharField(max_length=100, verbose_name="设备类型"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oil_records.attraction",
                        verbose_name="所属景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
            },
        ),
        migrations.CreateModel(
            name="OilInspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="报告日期")),
                ("sample_date", models.DateField(verbose_name="采样日期")),
                (
                    "report_number",
                    models.CharField(max_length=100, verbose_name="报告编号"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="oil_reports/", verbose_name="PDF报告文件"
                    ),
                ),
                (
                    "md_content",
                    models.TextField(blank=True, verbose_name="OCR生成的MD内容"),
                ),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="处理后的检测数据"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oil_records.equipment",
                        verbose_name="检测设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "油品检测报告",
                "verbose_name_plural": "油品检测报告",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="OilParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(max_length=100, verbose_name="参数名称"),
                ),
                ("parameter_value", models.FloatField(verbose_name="参数值")),
                ("unit", models.CharField(max_length=50, verbose_name="单位")),
                (
                    "standard_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="标准范围"
                    ),
                ),
                (
                    "is_normal",
                    models.BooleanField(default=True, verbose_name="是否正常"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oil_records.oilinspectionreport",
                        verbose_name="检测报告",
                    ),
                ),
            ],
            options={
                "verbose_name": "油品参数",
                "verbose_name_plural": "油品参数",
            },
        ),
    ]
