# Generated by Django 5.2.7 on 2025-11-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oil_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oilinspectionreport",
            name="report_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="报告编号"
            ),
        ),
    ]
