# Generated by Django 4.2.7 on 2026-03-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oil_records', '0002_alter_oilinspectionreport_report_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerrographyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='报告日期')),
                ('sample_date', models.DateField(verbose_name='采样日期')),
                ('report_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='报告编号')),
                ('pdf_file', models.FileField(upload_to='ferrography_reports/', verbose_name='PDF报告文件')),
                ('md_content', models.TextField(blank=True, verbose_name='OCR生成的MD内容')),
                ('processed_data', models.JSONField(blank=True, default=dict, verbose_name='处理后的检测数据')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oil_records.equipment', verbose_name='检测设备')),
            ],
            options={
                'verbose_name': '铁谱分析报告',
                'verbose_name_plural': '铁谱分析报告',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='FerrographyParticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particle_type', models.CharField(max_length=100, verbose_name='颗粒类型')),
                ('concentration', models.CharField(max_length=50, verbose_name='浓度')),
                ('size_range', models.CharField(blank=True, max_length=100, verbose_name='尺寸范围')),
                ('morphology', models.TextField(blank=True, verbose_name='形貌描述')),
                ('wear_mechanism', models.CharField(blank=True, max_length=200, verbose_name='磨损机理')),
                ('severity_level', models.CharField(blank=True, max_length=50, verbose_name='严重等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferrography_reports.ferrographyreport', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': '铁谱颗粒',
                'verbose_name_plural': '铁谱颗粒',
            },
        ),
        migrations.CreateModel(
            name='FerrographyDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_assessment', models.TextField(blank=True, verbose_name='总体评价')),
                ('wear_status', models.CharField(blank=True, max_length=200, verbose_name='磨损状态')),
                ('recommendations', models.TextField(blank=True, verbose_name='建议措施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ferrography_reports.ferrographyreport', verbose_name='所属报告')),
            ],
            options={
                'verbose_name': '铁谱诊断',
                'verbose_name_plural': '铁谱诊断',
            },
        ),
    ]
