# Generated by Django 4.2.7 on 2026-03-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferrography_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerrographyAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='景点名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '铁谱检测景点',
                'verbose_name_plural': '铁谱检测景点',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FerrographyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferrography_reports.ferrographyattraction', verbose_name='所属景点')),
            ],
            options={
                'verbose_name': '铁谱检测设备',
                'verbose_name_plural': '铁谱检测设备',
                'ordering': ['attraction__name', 'name'],
                'unique_together': {('attraction', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='ferrographyreport',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferrography_reports.ferrographyequipment', verbose_name='检测设备'),
        ),
    ]
