# Generated by Django 4.2.7 on 2026-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0002_add_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecrrecord',
            name='after_change_image',
            field=models.ImageField(blank=True, null=True, upload_to='ecr/after_change/%Y/%m/', verbose_name='变更后图片'),
        ),
        migrations.AddField(
            model_name='ecrrecord',
            name='before_change_image',
            field=models.ImageField(blank=True, null=True, upload_to='ecr/before_change/%Y/%m/', verbose_name='变更前图片'),
        ),
    ]
